services:
  db:
    image: postgres:17
    container_name: nbti-postgres
    environment:
      POSTGRES_USER: nbti
      POSTGRES_PASSWORD: nbti
      POSTGRES_DB: nbti
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nbti-network

volumes:
  pgdata:

networks:
  engin-network:
    driver: bridge
